### PR TITLE
mimimum page

### PR DESCRIPTION
**Pull request by boazdavid**
to support the need for fast creating simple apps - we created a simple page that show the minimum code. 
New applications should clone the 'minimum' folder and the app.js.

### CODE REVIEW

**Comment by germanattanasio** [comment]
The demo was updated: http://tradeoff-analytics-demo.mybluemix.net/

**Comment by jsstylos** [comment]
How long are we going to continue having two side-by-side demo versions? If
there aren't major problems with the new version I'd prefer to only have
one version up.

**Comment by boazdavid** [comment]
We are currently developing a v2 of the UI.  It is not mature yet. We expose it to the public hoping to collect feedback from users. 
The new UI is aimed to GA on the end of Q1. During that time both versions will be side by side (different URLs).
Even after v2 GA, we will continue to serve v1 for consumers that prefer to stay with the old UI.

**Comment by jsstylos** [comment]
We typically don't support side-by-side versions of demos or sample code
(other than git history and tags), because of the maintenance costs and
confusion for users (they shouldn't have to decide which version they
want). If there are reasons why v2 is unsuitable to replace v1 then we
should figure out a plan to get to one supported version.

**Comment by boazdavid** [comment]
Seems that there is a confusion. Tradeoff-Analytics has 3 types of assets: 1) Service API, 2) A web-UI library (on a CDN) that consumes the service, and 3) some sample apps.
Most of the apps use the UI library to improve user experience (others use the service api directly).
We are currently developing a new version for the UI library. Our official demos continue to refer to the old  version of the library. 
As the new library will be ready (end Q1), we will modify the demos to refer to the new library.
I hope it is clear now.

**Comment by jsstylos** [comment]
Ok, as long as by the end of Q1 we only have one demo url that should be
fine.

**Pull request merged**
