### PR TITLE
Enhance demo to demonstrate new CDN features (metadata and event collection) + some fixes

### PR DESCRIPTION
**Pull request by dolevdotan**

### CODE REVIEW

**Comment by germanattanasio** [comment]
This changes are associated with https://github.com/watson-developer-cloud/nodejs-wrapper/pull/97 so I will not merge them until we fix the nodejs wrapper since this changes depend on it.

**Comment by dolevdotan** [comment]
fixed node-js wrapper according to your request, aligned demo code accordingly

**Comment by dolevdotan** [comment]
OK, @germanattanasio, everything is ready in the wrapper... I also merged @boazdavid 's pull request so you don't have to accept twice...

Please accept the pull request so we can get this over with. Weekend is just upon us (here), and I'd like to report this over...

**Comment by dincerkurnaz** [comment]
#startup @quictransfer File Sharing Upload "share love!" https://quictransfer.com https://www.youtube.com/watch?v=6hgctnqE5Sg #RT 🚀🆓❤ SaaS

**Pull request merged**
